name: Docker Image CI

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package
      - name: Build image
        run: docker buildx build -t khacduy/ecommerce-spring:latest .
      - name: Push image
        run: |
          docker login -u khacduy -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push khacduy/ecommerce-spring:latest
          
          
