name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package
      - name: Build image
        run: docker buildx build -t khacduy/ecommerce-spring:latest .
      - name: Push image
        run: |
          docker login -u khacduy -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push khacduy/ecommerce-spring:latest
      - name: Deploy
        env: 
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
          
          
